# Generated by Django 5.1.1 on 2025-08-04 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='https://i.pravatar.cc/250?u=mail@ashallendesign.co.uk', upload_to='profiles/'),
        ),
    ]
