# Generated by Django 5.2.4 on 2025-08-22 11:49

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_delete_follow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='profiles/default.jpeg', storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='profiles/'),
        ),
    ]
